sm8650-common: Patch libsensorndkbridge to resolve duplicate dependencies
Fixes:
error: module "prebuilt_libsensorndkbridge" variant
"android_vendor_arm64_armv8-2a-dotprod_static": depends on multiple
versions of the same aidl_interface:
android.hardware.sensors-V2-ndk-source,
android.hardware.sensors-V3-ndk-source